version: 2

sources:
  - name: job_market_staging
    database: JOB_MARKET_DB
    schema: STAGING
    tables:
      - name: STG_JOOBLE_JOBS
      - name: STG_JSEARCH_JOBS
      - name: STG_FREEHIRE_JOBS
      - name: STG_TANQEEB_JOBS
      - name: STG_TEPNEO_JOBS   # خطأ إملائي فعلي بـ Snowflake (المقصود tapneo)